-- Add transcript_narrative column to store the human-readable markdown narrative
-- generated by Gemini for the Transcript tab in the report UI
ALTER TABLE analysis_results ADD COLUMN IF NOT EXISTS transcript_narrative TEXT;
